pipeline {
    agent any

    environment {
        GITHUB_REPO = 'https://github.com/ianramy/alx-backend-python.git'
        APP_DIR = 'messaging_app'
        VENV = 'venv'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: "${GITHUB_REPO}"
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './venv/bin/pytest --junitxml=test-results.xml'
            }
            post {
                always {
                    junit 'test-results.xml'
                }
            }
        }
    }
}
