#!/bin/bash

echo "Deploying blue and green versions..."
kubectl apply -f messaging_app/blue_deployment.yaml
kubectl apply -f messaging_app/green_deployment.yaml
kubectl apply -f messaging_app/kubeservice.yaml

echo "Checking logs for both deployments..."
kubectl logs -l app=messaging-app
kubectl logs -l app=messaging-app-green
